language: go
sudo: required
dist: trusty
go: "1.10"

services:
- docker

install: true
script:
  - make docker-generate
  - if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run make. Please run it and commit the changes"; git status --porcelain; false; fi
  - make docker-test

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-build docker-push
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-build docker-push IMAGE_TAG=$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
